# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ag-extension"
client_id = "1146ecd4bb7a38b93fd75f85aeb406c9"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_customer_tags"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "ins-checkout-extensibility.myshopify.com"
